"""GitHub issue drafter.

Default mode is dry_run=True (reads from settings).  When dry_run is True,
the issue payload is constructed and returned/saved but NO API call is made.
Pass dry_run=False (or set LOGSENSE_DRY_RUN=false) to actually create the issue.

This design is intentional for a public demo: nobody should accidentally
spam a real GitHub tracker.
"""

import json
import uuid
from datetime import datetime, timezone

import httpx

from logsense.config import get_settings
from logsense.rca.models import RCAResult
from logsense.triage.models import Cluster
from .models import IncidentDraft

_ISSUE_BODY_TEMPLATE = """\
## Incident Summary

**Affected Service:** `{affected_service}`
**Cluster Template:** `{template}`
**Occurrences:** {count} between `{first_seen}` and `{last_seen}`
**Severity:** {severity}
**Risk Score:** {risk_score:.3f}
**Confidence:** {confidence} ({confidence_score:.0%})

---

## Summary

{summary}

## Root Cause Hypothesis

{root_cause_hypothesis}

## Suggested Next Action

{suggested_action}

---

> 🤖 Generated by [LogSense](https://github.com/pavankumarale/logsense) — \
AI-powered log analysis agent
"""

_GITHUB_API_BASE = "https://api.github.com"


class GitHubIssueDrafter:
    def __init__(self, dry_run: bool | None = None) -> None:
        cfg = get_settings()
        self._dry_run = dry_run if dry_run is not None else cfg.dry_run
        self._token = cfg.github_token
        self._repo = cfg.github_repo

    def draft(self, rca: RCAResult, cluster: Cluster) -> IncidentDraft:
        """Build an issue payload.  If dry_run=False, also POST to GitHub."""
        labels = ["logsense", "auto-rca", rca.confidence]
        if cluster.max_severity in ("ERROR", "CRITICAL"):
            labels.append("severity:high")

        body = _ISSUE_BODY_TEMPLATE.format(
            affected_service=rca.affected_service,
            template=cluster.template,
            count=cluster.count,
            first_seen=cluster.first_seen.isoformat(),
            last_seen=cluster.last_seen.isoformat(),
            severity=cluster.max_severity,
            risk_score=cluster.risk_score,
            confidence=rca.confidence,
            confidence_score=rca.confidence_score,
            summary=rca.summary,
            root_cause_hypothesis=rca.root_cause_hypothesis,
            suggested_action=rca.suggested_action,
        )

        payload = {
            "title": f"[LogSense] {rca.title}",
            "body": body,
            "labels": labels,
        }

        external_url: str | None = None
        status = "draft"

        if not self._dry_run:
            external_url = self._create_issue(payload)
            status = "submitted"

        return IncidentDraft(
            id=str(uuid.uuid4()),
            rca_id=rca.id,
            platform="github",
            payload=payload,
            status=status,
            external_url=external_url,
            created_at=datetime.now(timezone.utc),
        )

    def _create_issue(self, payload: dict) -> str:
        if not self._token or not self._repo:
            raise ValueError(
                "GITHUB_TOKEN and GITHUB_REPO must be set to create real issues"
            )
        url = f"{_GITHUB_API_BASE}/repos/{self._repo}/issues"
        resp = httpx.post(
            url,
            headers={
                "Authorization": f"Bearer {self._token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            json=payload,
            timeout=30.0,
        )
        resp.raise_for_status()
        return resp.json()["html_url"]
